######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 16 23:23:25 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += gsm.c lcd12864.c
