set PATH=C:\Keil\C51\BIN
set C51INC=C:\KEIL\C51\INC;C:\Keil\C51\inc
set C51LIB=C:\KEIL\C51\LIB
C51.exe cheshi.C OPTIMIZE(9,SPEED)  BROWSE   DEBUG OBJECTEXTEND CODE 
@IF %ERRORLEVEL% GEQ 2 GOTO MERROR
BL51.exe cheshi.obj TO cheshi.omf RAMSIZE(256) IXREF
@IF %ERRORLEVEL% GEQ 2 GOTO MERROR
oh51.exe cheshi.omf
@IF %ERRORLEVEL% GEQ 2 GOTO MERROR
@ECHO Target Created Successfully !
@EXIT
:MERROR
@ECHO Target Not Created !
@EXIT
